### ISSUE TITLE
Unity generates an unescaped string

### ISSUE THREAD

**Issue by cyclingengineer** [ThrowTheSwitch/Unity#137]
Hi,

IAR generates a warning when using unity on this line of the test runner:
```
UnityBegin("tests\my_tests.c");
```
The warning is: 
```
Warning[Pe192]: unrecognized character escape sequence 
```

This string should be 
```
UnityBegin("tests\\my_tests.c");
```

Thanks,
Paul

**Comment by mvandervoord** [comment]
Paul:

Are you sure you have the cutting edge at this point? I believe this problem is already fixed. You're talking about a runner created from the generate_test_runner.rb script, right?

Mark

**Comment by dmurdin** [comment]
I had the same problem so I looked up the relevant line from  cutting edge generate_test_runner.rb and found:
`output.puts("  UnityBegin(\"#{filename.gsub(/\\/,'\\\\')}\");")`
This did not help for me, I had to modify this to:
`output.puts("  UnityBegin(\"#{filename.gsub(/\\/,'\\\\\\')}\");")`
In order for the generated c-file to have the correct double-back-slashes in the string.

**Comment by cyclingengineer** [comment]
@mvandervoord We updated recently (April) and still had this issue. We have done the modification as per @dmurdin so this problem still persisted then.

**Comment by mvandervoord** [comment]
Ok. I'm going to need more specifics about your situation, then. What platform are you on? What arguments are you calling generate_test_runner.rb with?
